[09/Sep/2013 22:13:54] ERROR [django.request:212] Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1180, in changelist_view
    self)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 73, in __init__
    self.query_set = self.get_query_set(request)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 303, in get_query_set
    use_distinct) = self.get_filters(request)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 101, in get_filters
    raise SuspiciousOperation("Filtering by %s not allowed" % key)
SuspiciousOperation: Filtering by password__startswith not allowed
[09/Sep/2013 22:16:50] ERROR [django.request:212] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 188, in select_template
    return get_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 272, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 327, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'trans', expected 'endblock'
[09/Sep/2013 22:18:09] ERROR [django.request:212] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 188, in select_template
    return get_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/defaulttags.py", line 1044, in load
    (taglib, e))
TemplateSyntaxError: 'l18n' is not a valid tag library: Template library l18n not found, tried django.templatetags.l18n,django.contrib.staticfiles.templatetags.l18n,django_extensions.templatetags.l18n,main.templatetags.l18n
[09/Sep/2013 22:18:55] ERROR [django.request:212] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 188, in select_template
    return get_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 272, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 327, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'trans', expected 'endblock'
[09/Sep/2013 22:19:58] ERROR [django.request:212] Internal Server Error: /
Traceback (most recent call last):
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = response.render()
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/test/utils.py", line 66, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader_tags.py", line 102, in render
    compiled_parent = self.get_parent(context)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader_tags.py", line 99, in get_parent
    return get_template(parent)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/Users/kirill/.virtualenvs/minotaurus/lib/python2.7/site-packages/django/template/loader.py", line 139, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: main/base.html
